default:
		@echo "Running app..."
		javac Main.java; java Main Kickstarter1.csv Kickstarter2.csv Kickstarter3.csv
		# javac Main.java; java Main test1 test2 test3
clean:
		@echo "Cleaning up..."
		rm *.class