merge:
		@echo "Running app..."
		javac Merge.java; java Merge Kickstarter1.csv Kickstarter2.csv Kickstarter3.csv
		# javac Merge.java; java Merge test1 test2 test3

search:
		@echo "searching string..."
		javac Search.java; java Search mergedFile.csv 0,

clean:
		@echo "Cleaning up..."
		rm *.class