today:
	@echo "chaning script.sh mode and execute to output 'Files_Created_Today.txt' ..."
	chmod 777 ./script.sh; javac Main.java; java Main ./script.sh

clean:
	@echo "Cleaning Up..."
	rm ./*.class
	rm ./Files_Created_Today.txt